discovery_page_block_html_1:
  default: ""
  type: string
discovery_page_block_html_2:
  default: ""
  type: string
discovery_page_block_html_3:
  default: ""
  type: string
discovery_page_top_block_html:
  default: ""
  type: string
discovery_page_block_html_1_dark:
  default: ""
  type: string
discovery_page_block_html_2_dark:
  default: ""
  type: string
discovery_page_block_html_3_dark:
  default: ""
  type: string
discovery_page_top_block_html_dark:
  default: ""
  type: string
discovery_categories_html:
  default: ""
  type: list
discovery_categories_mobile_html:
  default: ""
  type: list
topic_categories_html:
  default: ""
  type: list
topic_categories_mobile_html:
  default: ""
  type: list
